from enum import Enum

class MusicGenre(str, Enum):
    # Rock genres
    ROCK = "rock"
    CLASSIC_ROCK = "classic-rock"
    ALTERNATIVE_ROCK = "alternative-rock"
    INDIE_ROCK = "indie-rock"
    HARD_ROCK = "hard-rock"
    PUNK_ROCK = "punk-rock"
    GARAGE_ROCK = "garage-rock"
    FOLK_ROCK = "folk-rock"
    PSYCHEDELIC_ROCK = "psychedelic-rock"
    PROGRESSIVE_ROCK = "progressive-rock"
    GLAM_ROCK = "glam-rock"
    SOFT_ROCK = "soft-rock"
    BLUES_ROCK = "blues-rock"
    SOUTHERN_ROCK = "southern-rock"
    ART_ROCK = "art-rock"
    POST_ROCK = "post-rock"
    STONER_ROCK = "stoner-rock"
    HEAVY_METAL = "heavy-metal"

    # Jazz genres
    JAZZ = "jazz"
    TRADITIONAL_JAZZ = "traditional-jazz"
    SWING_JAZZ = "swing-jazz"
    BEBOP = "bebop"
    HARD_BOP = "hard-bop"
    COOL_JAZZ = "cool-jazz"
    MODERN_JAZZ = "modern-jazz"
    LATIN_JAZZ = "latin-jazz"
    SMOOTH_JAZZ = "smooth-jazz"
    FUSION_JAZZ = "fusion-jazz"
    FREE_JAZZ = "free-jazz"
    AVANT_GARDE_JAZZ = "avant-garde-jazz"

    # Electronic genres
    ELECTRONIC = "electronic"
    HOUSE = "house"
    TECHNO = "techno"
    TRANCE = "trance"
    DUBSTEP = "dubstep"
    AMBIENT = "ambient"
    DRUM_AND_BASS = "drum-and-bass"
    CHILL_OUT = "chill-out"
    SYNTHPOP = "synthpop"
    INDUSTRIAL = "industrial"

    # Pop genres
    POP = "pop"
    K_POP = "k-pop"
    J_POP = "j-pop"
    INDIE_POP = "indie-pop"
    POP_ROCK = "pop-rock"

    # Hip Hop and Rap genres
    HIP_HOP = "hip-hop"
    RAP = "rap"
    TRAP = "trap"
    GANGSTA_RAP = "gangsta-rap"
    EAST_COAST_HIP_HOP = "east-coast-hip-hop"
    WEST_COAST_HIP_HOP = "west-coast-hip-hop"
    SOUTHERN_HIP_HOP = "southern-hip-hop"
    ALTERNATIVE_HIP_HOP = "alternative-hip-hop"

    # Other genres and subgenres
    BLUES = "blues"
    COUNTRY = "country"
    FOLK = "folk"
    REGGAE = "reggae"
    SOUL = "soul"
    FUNK = "funk"
    GOSPEL = "gospel"
    LATIN = "latin"
    REGGAETON = "reggaeton"
    AFROBEATS = "afrobeats"
    DANCE = "dance"
    MOOMBAHTON = "moombahton"
    SKA = "ska"
    EMO = "emo"
    GRUNGE = "grunge"
    PUNK = "punk"
    GARAGE = "garage"
    NEW_AGE = "new-age"
    OPERA = "opera"
    BLUEGRASS = "bluegrass"
    TRIP_HOP = "trip-hop"
    WORLD = "world"
    DISCO = "disco"
    SINGER_SONGWRITER = "singer-songwriter"
    # Add more genres as needed
